### ISSUE TITLE
release version v2.0

### ISSUE THREAD

**Issue by williballenthin** [mandiant/flare-floss#387]
[milestone v2.0 here](https://github.com/fireeye/flare-floss/milestone/8)

major goals:
  - [x] upgrade to python 3 (breaking change) #386
  - [x] revamp CI and packaging
  - [x] add FLIRT matching to ignore library functions #285
  - [x] update cli arguments and output format (breaking change) #385
