### ISSUE TITLE
Add test cases to CI

### ISSUE THREAD

**Issue by mr-tz** [mandiant/flare-floss#807]
To ensure our algorithms work across a variety of Go samples:

```[tasklist]
### Tasks
- [x] know expected strings for all tracked Go versions: https://github.com/mandiant/flare-floss-testfiles/tree/master/src/go-binaries-all-versions
- [x] add test samples of Go sample where source is unknown
- [x] using script from #806 ensure we at least cover x% of strings
```

**Comment by mr-tz** [comment]
@Arker123, can you please make sure all points are covered here and add tests if necessary?

**Comment by mr-tz** [comment]
we should add tests for the Go samples @Arker123 generated for various Go versions

**Comment by Arker123** [comment]
Hey, during testing, I made a discovery. Our program successfully extracted the following strings from the sample code used for compiling the binaries with a version greater than or equal to go1.12:

    "Something is wrong with your computer"
    "You Cracked it, A Hero is born"
    "Don't Worry, Relax, Chill and Try harder"
    "Enter Password:"

These strings were successfully identified and extracted by our program.

**Comment by Arker123** [comment]
However, I must inform you that this functionality doesn't seem to work for binaries compiled with go1.11

**Comment by Arker123** [comment]
Additionally, I was wondering if you have any suggestions on how I can add a test for the binaries located at https://github.com/Arker123/flare-floss-testfiles/tree/master/src/go-binaries-all-versions/bin. The challenge is that these binaries are actually compressed in a zip file. It's an interesting hurdle to overcome! 😅

**Comment by Arker123** [comment]
During the development of the Go coverage script, the value we needed to determine was previously determined through guessing. 
![image](https://github.com/mandiant/flare-floss/assets/94680887/6e6905a7-f72d-46a6-af5b-234ade0a13bd)

To visualize this process, I plotted the results on a graph.
To determine the appropriate value, I adopted a brute force approach and experimented with different ranges. 
Initially, I used a range with start = 10, end = 1000, and step = 200. The graph below shows the results of this range:

![image](https://github.com/mandiant/flare-floss/assets/94680887/0a7e5c49-9dbf-4f48-87cd-03c967341cc3)

After narrowing down the range, we further experimented with start = 1650, end = 3200, and step = 50. The graph below illustrates the results obtained from this range:
![image](https://github.com/mandiant/flare-floss/assets/94680887/d4d7a0ac-9d34-4d3e-be1f-2653b9d5ea55)

Based on the insights gained from analyzing the graph, I concluded that the optimal value for our purpose was 2800. This value provided accuracy greater than 90% for all files.


To explore the code used for this analysis, refer to the following link: https://gist.github.com/Arker123/c25ac6514ff2aa34656b3aecf5f3372e

The code was tested on various versions of go binaries and architectures, see https://github.com/mandiant/flare-floss-testfiles/pull/12

**Comment by mr-tz** [comment]
> Additionally, I was wondering if you have any suggestions on how I can add a test for the binaries located at https://github.com/Arker123/flare-floss-testfiles/tree/master/src/go-binaries-all-versions/bin. The challenge is that these binaries are actually compressed in a zip file. It's an interesting hurdle to overcome! 😅

Can you unzip the file as part of the test, potentially via a fixture or test prep, and then run on each file?
