### ISSUE TITLE
Go strings integration tasks

### ISSUE THREAD

**Issue by mr-tz** [mandiant/flare-floss#826]
```[tasklist]
### Tasks
- [x] render `\t` vs. tab (strings.exe does the latter)
- [x] Go build ID string split into multiple lines, see image1?
- [x] strings split, see image 2?
```

image 1
<img width="626" alt="2023-07-12_12-24-33_WindowsTerminal" src="https://github.com/mandiant/flare-floss/assets/17606537/43711a7d-07ee-463f-ac8e-61bf0bdb19fe">

image 2
<img width="1546" alt="2023-07-12_11-29-15_WinMergeU" src="https://github.com/mandiant/flare-floss/assets/17606537/c61df6ef-f3b2-4363-8306-1d0e71e92840">

**Comment by Arker123** [comment]
> For task 2 and 3 I think the `console` setting (width) results in the added new lines...

So, to address this, should I increase the width setting?

**Comment by williballenthin** [comment]
if the case is what @mr-tz mentioned, then its `rich` deciding to wrap the string across multiple lines, based on the current width of the terminal. we should decide what the behavior should be. i think two reasonable options include:

  - don't wrap, and truncate strings at the end of the terminal, though this potentially makes it difficult to review the complete string contents
  - don't wrap, and let the terminal wrap long lines, as strings.exe does. i dont think blindly changing the console width is the right fix here, since i can trivially construct a string that's longer than whatever width you pick. instead, we should read more about `rich` and how to change the behavior.

**Comment by mr-tz** [comment]
> > render `\t` vs. tab (strings.exe does the latter)
> 
> Is this feature already in place?
> 
> ![image](https://user-images.githubusercontent.com/94680887/261846893-e22b4b40-46ff-4551-acbc-78c3446508e2.png)

we need to decide which behavior we want and make sure it's consistent across the output functions

is that the case currently?

**Comment by mr-tz** [comment]
Ok, then we only have the wrapping issue left to fix.

**Comment by mr-tz** [comment]
closed via #861
