### ISSUE TITLE
Update documentation and release new version

### ISSUE THREAD

**Issue by mr-tz** [mandiant/flare-floss#866]
```[tasklist]
### Tasks
- [x] update documentation
- [ ] https://github.com/mandiant/flare-floss/issues/875
- [ ] test language extraction and integration
- [ ] write blog post
- [ ] release (v3) - https://github.com/mandiant/flare-floss/pull/903
```
